{
 "title": "Resilience4j Metrics",
 "description": "Resilience4j Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(resilience4j_circuitbreaker_state,instance)"
    }
   },
   {
    "name": "circuitbreaker_name",
    "label": "CircuitBreaker Name",
    "query": {
     "query": "label_values(resilience4j_circuitbreaker_state,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of closed CircuitBreaker",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=\"closed\"})"
    }
   ]
  },
  {
   "title": "Number of open CircuitBreaker",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=~\"open|forced_open\"})"
    }
   ]
  },
  {
   "title": "CircuitBreaker States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{}",
     "legendFormat": "{{ name }}: {{ state }}"
    }
   ]
  },
  {
   "title": "Number of half_open CircuitBreaker",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=\"half_open\"})"
    }
   ]
  },
  {
   "title": "CircuitBreaker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "circuitbreaker_name",
   "targets": [
    {}
   ]
  },
  {
   "title": "Failure Rate: $circuitbreaker_name",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failure_rate{instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Call rate: $circuitbreaker_name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Calls/sec" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }} "
    },
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_total{name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind  }} "
    }
   ]
  },
  {
   "title": "Call duration percentiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "98th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Average call durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "increase(resilience4j_circuitbreaker_calls_seconds_sum{name=\"$circuitbreaker_name\"}[1m]) / increase(resilience4j_circuitbreaker_calls_seconds_count{name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "sum(increase(resilience4j_circuitbreaker_calls_seconds_sum{name=\"$circuitbreaker_name\"}[1m])) / sum(increase(resilience4j_circuitbreaker_calls_seconds_count{name=\"$circuitbreaker_name\"}[1m]))",
     "legendFormat": "total "
    }
   ]
  }
 ]
}