version: '3.8'

services:
  library:
    build:
      context: .
      target: production
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/librarydb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      main:
  postgres:
    image: "postgres:15.3"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=librarydb
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    networks:
      main:
  grafana:
    build: './docker/config/grafana'
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
  prometheus:
    image: "prom/prometheus:v2.45.0"
    ports:
      - "9090:9090"
    volumes:
      - ./docker/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/prometheus:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      monitoring:
networks:
  main:
  monitoring: