spring:
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:h2:file:./db/librarydb
  #    h2:
  #      console:
  #        path: /h2-console
  #        settings:
  #          web-allow-others: true
  #        enabled: true
  jpa:
    #    generate-ddl: true
    hibernate:
      ddl-auto: validate
    #    properties:
    #      hibernate:
    #        format_sql: true
    show-sql: true
  liquibase:
    enabled: true
  sql:
    init:
      mode: never
management:
  endpoints:
    jmx:
      exposure:
        include: "health,logfile"
    web:
      exposure:
        include: "health,logfile,prometheus"
    enabled-by-default: false
  endpoint:
    health:
      show-details: always
      enabled: true
    logfile:
      enabled: true
    prometheus:
      enabled: true
  health:
    defaults:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
logging:
  level:
    ROOT: ERROR
    web: debug
    # web: trace
    com.github.kondury: debug
  file:
    name: ./log/library.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log.gz
      max-file-size: 100KB
